The generated application contains a `BookController`. It responds to POST request to `/`.

[source,groovy]
.src/main/groovy/example/micronaut/BookController.groovy
----
include::{sourceDir}/src/main/groovy/example/micronaut/BookController.groovy[]
----

<1> The class is defined as a controller with the `@Controller` annotation mapped to the path /
<2> The `@Post` annotation is used to map HTTP request to `/` to the the `save` method.
<3> Add the `@Valid` annotation to any method parameter's object which requires validation.

The controller's method parameter is a `Book` object:

[source,groovy]
.src/main/groovy/example/micronaut/Book.groovy
----
include::{sourceDir}/src/main/groovy/example/micronaut/Book.groovy[]
----

<1> Annotate the class with `@Introspected` to generate the Bean Metainformation at compile time.
<2> `name` is required
<3> Add a nullability annotation to help with Kotlin interoperability and help the IDE.

It returns a `BookSaved` object:

[source,groovy]
.src/main/groovy/example/micronaut/BookSaved.groovy
----
include::{sourceDir}/src/main/groovy/example/micronaut/BookSaved.groovy[]
----

<1> Annotate the class with `@Introspected` to generate the Bean Metainformation at compile time.
<2> `name` and `isbn` are required
<3> Add a nullability annotation to help with Kotlin interoperability and help the IDE.


The generated tests illustrates how the code works when the lambda gets invoked:

[source,groovy]
.src/test/groovy/example/micronaut/BookControllerSpec.groovy
----
include::{sourceDir}/src/test/groovy/example/micronaut/BookControllerSpec.groovy[]
----

<1> When you instantiate the Handler, the application context starts.
<2> Remember to close your application context when you end your test. You can use your handler to obtain it.
<3> You don't invoke the controller directly. Instead, your handler receives a AWS Proxy Request event which it is routed transparently to your controller.